const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

function assertIncludes(file, needle, message) {
  assert.ok(read(file).includes(needle), `${file}: ${message}`);
}

function assertNotIncludes(file, needle, message) {
  assert.ok(!read(file).includes(needle), `${file}: ${message}`);
}

assertIncludes("components/UploadStep.tsx", 'type="file"', "upload step must include a native file input");
assertIncludes("components/UploadStep.tsx", "onDrop", "upload step must support drag and drop");
assertIncludes("components/UploadStep.tsx", "uploadedFiles", "upload step must render selected file state");
assertIncludes("components/UploadStep.tsx", "product-image-upload", "upload step must expose a separate product image input");
assertIncludes("components/UploadStep.tsx", "report-file-upload", "upload step must expose a separate report input");
assertIncludes("components/UploadStep.tsx", "document-file-upload", "upload step must expose a separate document input");
assertIncludes("components/UploadStep.tsx", "onAnalyze", "upload step must trigger AI material analysis");
assertIncludes("components/UploadStep.tsx", "手动补充信息（可不填）", "upload sidebar must expose optional manual product fields");
assertIncludes("components/UploadStep.tsx", "onManualFieldChange", "upload sidebar must propagate manual field edits");
assertIncludes("components/UploadStep.tsx", "manualFieldKeys", "upload sidebar must show which fields are manually prioritized");
assertNotIncludes("components/StyleStep.tsx", 'id="category"', "style step must not expose a manual category selector");
assertNotIncludes("components/StyleStep.tsx", "onCategoryChange", "style step must not wire manual category changes");
assertNotIncludes("components/StyleStep.tsx", "风格参考图", "style reference image section should be removed from style selection");
assertNotIncludes("components/StyleStep.tsx", "style-reference-upload", "style step should not expose style reference uploads");
assertNotIncludes("components/UploadStep.tsx", "风格参考", "upload summary should not show the removed style reference count");
assertNotIncludes("app/page.tsx", "onStyleReferenceSelect", "page should not wire the removed style reference selector");
assertNotIncludes("app/page.tsx", "onStyleFilesAdded", "page should not wire style reference uploads into the style step");
assertNotIncludes("app/page.tsx", "请先上传并选择风格参考图", "generation should not block on removed style reference mode");
assertIncludes("lib/api.ts", "analyzeUploadedMaterials", "frontend API must send uploaded materials for AI analysis");
assertNotIncludes("lib/api.ts", "analyzeProductVisual", "frontend API must not use a separate product visual suggestion step");
assertNotIncludes("lib/api.ts", "/api/projects/analyze-product-visual", "frontend API must not call a separate product visual suggestion endpoint");
assertIncludes("lib/productInfo.ts", "mergeProductInfoWithManualPriority", "product info helper must preserve manual fields when AI returns data");
assertIncludes("app/page.tsx", "mergeProductInfoWithManualPriority", "page must merge AI analysis results without overwriting manual fields");
assertIncludes("lib/api.ts", "http://127.0.0.1:8000", "frontend API should default to the backend bind address");
assertIncludes("lib/api.ts", 'credentials: "include"', "frontend API requests must include the SSO session cookie");
assertIncludes("lib/api.ts", "redirectToMainAppIfNeeded", "frontend API requests must redirect to the main site on SSO 401 responses");
assertIncludes("middleware.ts", "ssoError", "middleware must tell the main site when ticket exchange fails");
assertIncludes("lib/api.ts", "AbortController", "frontend API requests must time out instead of leaving the app loading forever");
assertIncludes("lib/api.ts", "createGenerateImageJob", "image generation must create a backend job instead of holding one long request");
assertIncludes("lib/api.ts", "fetchGenerateImageJob", "image generation must poll the backend generation job");
assertIncludes("lib/api.ts", "pollGenerateImageJob", "image generation must wait for job completion through short polling requests");
assertIncludes("lib/api.ts", "/api/projects/generate/jobs", "frontend image generation must use the backend job endpoint");
assertNotIncludes("lib/api.ts", "timeoutMs: 600000\n    });\n  } catch (error) {\n    rethrowMainAppRedirect(error);\n    return {\n      source: \"demo\"", "image generation must not wait on a single long synchronous request");
assertIncludes("lib/api.ts", "timeoutMs: 180000", "material analysis must keep the request open long enough for model output");
assertIncludes("lib/constants.ts", 'defaults: { size: "2048x2048"', "frontend demo model config must reflect 2K image generation defaults");
assertIncludes("app/page.tsx", "selectedPlatform.generationSize", "page image generation requests must use the 2K generation size");
assertIncludes("app/page.tsx", "editGeneratedImage(imageUrl, trimmed, selectedPlatform.generationSize, selectedImageModelId)", "image edits must keep the selected platform 2K generation size and selected image model");
assertIncludes("components/ModulesStep.tsx", "选择图片模型", "modules step must expose the image model selector");
assertIncludes("lib/api.ts", "image_model_id: imageModelId", "frontend generation/edit requests must send the selected image model id");
assertNotIncludes("lib/api.ts", 'source: "demo"', "frontend must not convert failed image generation into fixed demo images");
assertNotIncludes("lib/api.ts", "/assets/generated-cica-asset-sheet.png", "frontend must not mark fixed demo images as generated output");
assert.ok(!fs.existsSync(path.join(root, "lib/autoGenerate.ts")), "lib/autoGenerate.ts: full auto generation flow should be removed");
assert.ok(!fs.existsSync(path.join(root, "components/AutoUploadStep.tsx")), "components/AutoUploadStep.tsx: full auto upload step should be removed");
assert.ok(!fs.existsSync(path.join(root, "components/AutoProgressStep.tsx")), "components/AutoProgressStep.tsx: full auto progress step should be removed");
assert.ok(!fs.existsSync(path.join(root, "components/AutoResultStep.tsx")), "components/AutoResultStep.tsx: full auto result step should be removed");
assertIncludes("components/ModulesStep.tsx", "{platform.name} · 生成 {platform.generationSize}", "platform selector must show the 2K generation size first");
assertIncludes("components/ModulesStep.tsx", "生成尺寸 {selectedPlatform.generationSize}", "platform summary must lead with actual generation size");
assertIncludes("components/ModulesStep.tsx", "发布参考：主图 {selectedPlatform.mainSize}", "platform summary may show platform publishing size only as a reference");
assertIncludes("components/ModulesStep.tsx", "当前平台生成尺寸 {selectedPlatform.generationSize}", "model panel must show the actual 2K request size");

assertIncludes("components/ReviewStep.tsx", "textarea", "review step must allow editing extracted fields");
assertIncludes("components/ReviewStep.tsx", "onUpdateProductInfo", "review step must propagate edits to page state");
assertIncludes("components/ReviewStep.tsx", "confirmedFields", "review step must track field confirmation");
assertIncludes("components/ReviewStep.tsx", "暂无 AI 提炼结果", "review step must be empty until real AI extraction succeeds");
assertNotIncludes("app/page.tsx", "setProductInfo(defaults.product_info)", "page must not prefill review fields with demo product information");
assertIncludes("app/page.tsx", "hasAiProductInfo ? productInfo : null", "review step must render extracted fields only after a model result");
assertIncludes("app/page.tsx", 'result.source === "model" && result.product_info', "page must require a real model product_info before filling review fields");
assertNotIncludes("lib/api.ts", "DEFAULT_PRODUCT_INFO", "frontend API must not fall back to demo product information");
assertNotIncludes("lib/constants.ts", "DEFAULT_PRODUCT_INFO", "frontend constants must not ship demo product information");

assertIncludes("components/PreviewStep.tsx", "download", "preview step must expose downloadable outputs");
assertIncludes("components/PreviewStep.tsx", "groupedItems.detail.map", "preview step must render every generated detail image in the long preview");
assertNotIncludes("components/PreviewStep.tsx", "generatedImages[0]?.url", "preview step must not use only the first generated image as the full long preview");
assertIncludes("components/PreviewStep.tsx", "createComposeLongImageJob", "preview step must start backend JPEG composition for the full long image");
assertIncludes("components/PreviewStep.tsx", "prepareComposeLongImageSources", "preview step must upload data URL sources before creating the compose job");
assertIncludes("components/PreviewStep.tsx", "fetchComposeLongImageJob", "preview step must poll backend JPEG composition progress");
assertIncludes("components/PreviewStep.tsx", "composeStatus", "preview step must show backend progress during composition");
assertIncludes("components/PreviewStep.tsx", "full-detail.jpg", "full long image export must download a JPG file");
assertNotIncludes("components/PreviewStep.tsx", "full-detail.svg", "full long image export must not download SVG");
assertNotIncludes("components/PreviewStep.tsx", "window.open", "image downloads must not open popup tabs when direct fetch fails");
assertNotIncludes("components/PreviewStep.tsx", "window.location.href = download.url", "long image downloads must not navigate to remote image URLs");
assertIncludes("components/PreviewStep.tsx", "handleDownloadVisibleBatch", "preview directory must expose batch download for the active main/campaign group");
assertIncludes("components/PreviewStep.tsx", "index < visibleItems.length", "batch download must only download currently generated images in the active directory");
assertIncludes("components/PreviewStep.tsx", 'activeImageGroup === "detail"', "detail directory must keep compose download separate from main/campaign batch download");
assertIncludes("components/PreviewStep.tsx", "批量下载", "main and campaign directories must show a batch download action");
assertIncludes("lib/api.ts", "/api/projects/compose-long-image", "frontend API must expose backend long image composition");
assertIncludes("lib/api.ts", "/api/projects/compose-long-image/prepare", "frontend API must expose backend compose source preparation");
assertIncludes("app/page.tsx", "PROJECT_STATE_STORAGE_KEY", "page must define a storage key for preserving generated results");
assertIncludes("app/page.tsx", "localStorage", "page must persist generated results across reloads and step changes");
assertIncludes("app/page.tsx", "restored.generatedImages", "page must restore generated images from saved state");
assertIncludes("app/page.tsx", "window.location.hash", "page must restore active step from the URL hash");
assertIncludes("app/page.tsx", "hashchange", "page must stay in sync when the URL hash changes");
assertIncludes("app/page.tsx", "generationProgress", "page must track generation progress by image group");
assertIncludes("app/page.tsx", "promotionInfo", "page must persist campaign promotion text");
assertIncludes("app/page.tsx", "currentHistoryId", "page must keep the saved history id for later autosaves");
assertIncludes("app/page.tsx", "id: resolveReusableHistoryId(currentHistoryId, null)", "history autosave must reuse the current history id instead of inserting duplicates");
assertIncludes("lib/historyApi.ts", "LOCAL_HISTORY_STORAGE_KEY", "history API must keep a local fallback when PostgreSQL is not configured");
assertIncludes("lib/historyApi.ts", "getScopedLocalHistoryStorageKey", "history local fallback key must be scoped by session user");
assertIncludes("lib/historyApi.ts", "detail-image-agent-history:", "history local fallback key must include the current user id");
assertIncludes("lib/historyApi.ts", "fetchCurrentHistoryUserId", "history API must resolve the current SSO user before using local fallback history");
assertIncludes("lib/historyApi.ts", "saveLocalHistory", "history save must persist locally when the backend save fails");
assertIncludes("lib/historyApi.ts", "fetchLocalHistoryList", "history drawer must still show locally saved records when the backend list is empty");
assertIncludes("app/page.tsx", "defaultModules", "page must keep the default module config for a full new-project reset");
assertIncludes("app/page.tsx", "startNewProject", "page must expose a full new-project reset action");
assertIncludes("app/page.tsx", "setSelectedStyleId(styles[0]?.id ?? \"green_repair\")", "new project reset must restore the default style instead of copying the previous project style");
assertIncludes("app/page.tsx", "setSelectedPlatformId(\"tmall\")", "new project reset must restore the default platform instead of copying the previous project platform");
assertIncludes("app/page.tsx", "setModules(defaultModules.map((module) => ({ ...module })))", "new project reset must restore default modules instead of copying current module choices");
assertIncludes("app/page.tsx", "setPromotionInfo(\"\")", "new project reset must clear campaign promotion text");
assertIncludes("app/page.tsx", "setReturnWorkspaceSnapshot(null)", "new project reset must discard the previous workspace copy context");
assertNotIncludes("app/page.tsx", "duplicateProjectForNewProduct", "page must not keep copy-project behavior when starting a new project");
assertIncludes("app/page.tsx", "新建项目", "topbar action must communicate a new project reset");
assertNotIncludes("app/page.tsx", "复制项目", "topbar action must not describe the reset as copying");
assertIncludes("app/page.tsx", "returnWorkspaceSnapshot", "page must keep a return snapshot before loading a history copy");
assertIncludes("app/page.tsx", "useAppViewer", "page must load the SSO viewer before account-scoped history behavior");
assertIncludes("app/page.tsx", "setCurrentHistoryId(null)", "loading a history copy must start a new autosave record instead of overwriting the source history");
assertIncludes("app/page.tsx", "返回原工作区", "page must expose a way back to the original workspace after loading a history copy");
assertIncludes("components/HistoryDrawer.tsx", "onRestoreCopy(detail.state, detail.id)", "history drawer must load records as copies rather than continuing the source history id");
assertIncludes("components/HistoryDrawer.tsx", "载入副本", "history drawer restore action must communicate copy semantics");
assertNotIncludes("components/HistoryDrawer.tsx", "onRestore(detail.state, detail.id)", "history drawer must not pass the source history id for autosave reuse");
assertIncludes("lib/api.ts", "promotion_info", "frontend API must send campaign promotion text to backend generation");
assertNotIncludes("app/page.tsx", 'file.slot === "style_reference"', "page generation handler should not collect removed style reference uploads");
assertIncludes("lib/types.ts", 'StyleSource = "preset" | "ai_custom"', "frontend should model only preset and AI custom style sources");
assertIncludes("app/page.tsx", "setStyleSource(\"preset\")", "preset style selection must leave reference style mode");
assertNotIncludes("app/page.tsx", "setStyleSource(\"reference\")", "page should not offer removed reference style mode");
assertIncludes("components/StyleStep.tsx", "styleSource === \"preset\" && style.id === selectedStyleId", "preset cards must only be selected in preset style mode");
assertNotIncludes("components/StyleStep.tsx", "styleSource === \"reference\"", "style step should not render removed reference style mode");
assertNotIncludes("components/StyleStep.tsx", "onStyleReferenceSelect", "style step should not expose removed reference style handler");
assertIncludes("lib/api.ts", "planAiCustomStyle", "frontend API must expose Gemini custom style planning");
assertIncludes("lib/api.ts", "/api/projects/plan-style", "frontend API must call the backend style planning endpoint");
assertNotIncludes("lib/api.ts", "category,", "custom style planning must not send a manually selected category");
assertNotIncludes("app/page.tsx", "planAiCustomStyle(productInfo, selectedCategory", "custom style planning must rely on AI product_info category");
assertNotIncludes("app/page.tsx", "productInfo.category || selectedCategory", "history records must not fall back to a manually selected category");
assertIncludes("lib/api.ts", "product_images: productImages", "custom style planning must send product images directly to Gemini");
assertIncludes("lib/api.ts", "generateAiCustomStyleSample", "frontend API must expose custom style sample generation");
assertIncludes("lib/api.ts", "/api/projects/plan-style-sample", "frontend API must call the style sample endpoint separately");
assertNotIncludes("components/StyleStep.tsx", "Gemini 产品视觉建议", "style step must not display a separate product visual suggestion panel");
assertNotIncludes("app/page.tsx", "setProductVisualSuggestion", "page must not store separate visual suggestions before style planning");
assertIncludes("app/page.tsx", "const productImages = uploadedFiles", "page must collect uploaded product images for Gemini style planning");
assertIncludes("app/page.tsx", "customStyle", "page must store the Gemini-planned custom style");
assertIncludes("app/page.tsx", "planAiCustomStyle", "page must call Gemini only from the AI custom style action");
assertIncludes("app/page.tsx", "generateAiCustomStyleSample", "page must generate AI style samples only from the separate sample action");
assertIncludes("app/page.tsx", "styleSource === \"ai_custom\" ? customStyle", "generation must send the selected AI custom style brief");
assertIncludes("components/StyleStep.tsx", "customStyle.asset", "AI custom style card must render the generated GPT image sample when available");
assertIncludes("components/StyleStep.tsx", "让 AI 规划风格", "AI custom style action must only communicate style planning");
assertIncludes("components/StyleStep.tsx", "生成样例图", "AI custom style card must expose separate sample generation");
assertIncludes("app/page.tsx", "WHITE_BACKGROUND_MODULE_IDS", "page must recognize white background modules");
assertIncludes("app/page.tsx", "白底图需要先上传产品图", "white background regeneration must stop when the original product image is unavailable");
assertIncludes("components/StyleStep.tsx", "AI 自定义风格", "style step must show an AI custom style option");
assertNotIncludes("components/StyleStep.tsx", "Gemini 3.1 Pro</em>", "AI custom style card must not show a Gemini model badge");
assertIncludes("components/StyleStep.tsx", "aiPlanButton", "AI planning action should sit lower in the custom style card");
assertIncludes("components/StyleStep.tsx", "onPlanAiCustomStyle", "style step must expose a click handler for Gemini style planning");
assertIncludes("components/StyleStep.tsx", "onGenerateAiStyleSample", "style step must expose a separate sample generation handler");
assertIncludes("components/ModulesStep.tsx", "促销方式", "modules step must let users enter campaign promotion text");
assertIncludes("components/ModulesStep.tsx", "campaign", "modules step must expose campaign image generation group");
assertIncludes("components/PreviewStep.tsx", "campaign", "preview step must expose campaign image results");
assertIncludes("components/ModulesStep.tsx", "disabled={activeProgress.isGenerating}", "generation button must prevent duplicate submissions per image group");
assertIncludes("app/page.tsx", "runningModuleIds", "page generation progress must track every concurrently running module");
assertIncludes("components/ModulesStep.tsx", "(activeProgress.runningModuleIds ?? []).includes(module.id)", "modules step must show every concurrently running module as generating and tolerate restored progress state");
assertIncludes("components/PreviewStep.tsx", "(activeProgress.runningModuleIds ?? []).includes(module.id)", "preview step must show every concurrently running module as generating and tolerate restored progress state");
assertIncludes("app/page.tsx", "targetModuleId", "page generation handler must support a single target module");
assertIncludes("components/ModulesStep.tsx", "stopPropagation", "per-module generation buttons must not toggle module selection");
assertIncludes("components/ModulesStep.tsx", "重新生成", "modules step must expose regenerate actions");
assertIncludes("components/PreviewStep.tsx", "onGenerateModule", "preview step must trigger per-module regeneration");
assertIncludes("components/ModulesStep.tsx", "role=\"button\"", "module rows must remain keyboard-accessible after adding nested action buttons");
assertIncludes("components/ModulesStep.tsx", "preventDefault", "keyboard module toggles must not scroll the page");
assertIncludes("components/PreviewStep.tsx", "重新生成", "preview step must expose regenerate actions");

console.log("Static UI contract checks passed.");
