const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

function assertIncludes(file, needle, message) {
  assert.ok(read(file).includes(needle), `${file}: ${message}`);
}

function assertNotIncludes(file, needle, message) {
  assert.ok(!read(file).includes(needle), `${file}: ${message}`);
}

assertIncludes("components/UploadStep.tsx", 'type="file"', "upload step must include a native file input");
assertIncludes("components/UploadStep.tsx", "onDrop", "upload step must support drag and drop");
assertIncludes("components/UploadStep.tsx", "uploadedFiles", "upload step must render selected file state");
assertIncludes("components/UploadStep.tsx", "product-image-upload", "upload step must expose a separate product image input");
assertIncludes("components/UploadStep.tsx", "report-file-upload", "upload step must expose a separate report input");
assertIncludes("components/UploadStep.tsx", "document-file-upload", "upload step must expose a separate document input");
assertIncludes("components/UploadStep.tsx", "onAnalyze", "upload step must trigger AI material analysis");
assertIncludes("components/UploadStep.tsx", "详情图排版结构", "upload step must let users choose the detail layout before analysis");
assertIncludes("components/UploadStep.tsx", "onDetailLayoutChange", "upload step must propagate detail layout changes");
assertIncludes("components/UploadStep.tsx", "手动补充信息（可不填）", "upload sidebar must expose optional manual product fields");
assertIncludes("components/UploadStep.tsx", "productInfoFieldsForDetailLayout(selectedDetailLayoutId)", "upload manual fields must follow the selected detail layout");
assertIncludes("components/UploadStep.tsx", "onManualFieldChange", "upload sidebar must propagate manual field edits");
assertIncludes("components/UploadStep.tsx", "manualFieldKeys", "upload sidebar must show which fields are manually prioritized");
assertNotIncludes("components/StyleStep.tsx", 'id="category"', "style step must not expose a manual category selector");
assertNotIncludes("components/StyleStep.tsx", "onCategoryChange", "style step must not wire manual category changes");
assertIncludes("components/StyleStep.tsx", "图片对标", "style step must expose image benchmarking inside style selection");
assertIncludes("components/StyleStep.tsx", "style-reference-upload", "style step must expose a style reference upload input");
assertIncludes("components/StyleStep.tsx", "onStyleReferenceFilesAdded", "style step must pass uploaded benchmark images to the page");
assertIncludes("components/StyleStep.tsx", "onAnalyzeStyleReference", "style step must trigger Gemini benchmark image style analysis");
assertNotIncludes("components/UploadStep.tsx", "风格参考", "upload summary should not show the removed style reference count");
assertNotIncludes("app/page.tsx", "onStyleReferenceSelect", "page should not wire the removed style reference selector");
assertNotIncludes("app/page.tsx", "onStyleFilesAdded", "page should not wire style reference uploads into the style step");
assertNotIncludes("app/page.tsx", "请先上传并选择风格参考图", "generation should not block on removed style reference mode");
assertIncludes("lib/api.ts", "analyzeUploadedMaterials", "frontend API must send uploaded materials for AI analysis");
assertIncludes("lib/api.ts", "detail_layout_id: detailLayoutId", "material analysis must send the selected detail layout id");
assertNotIncludes("lib/api.ts", "analyzeProductVisual", "frontend API must not use a separate product visual suggestion step");
assertNotIncludes("lib/api.ts", "/api/projects/analyze-product-visual", "frontend API must not call a separate product visual suggestion endpoint");
assertIncludes("lib/productInfo.ts", "mergeProductInfoWithManualPriority", "product info helper must preserve manual fields when AI returns data");
assertIncludes("app/page.tsx", "mergeProductInfoWithManualPriority", "page must merge AI analysis results without overwriting manual fields");
assertIncludes("lib/api.ts", "http://127.0.0.1:8000", "frontend API should default to the backend bind address");
assertIncludes("lib/api.ts", 'credentials: "include"', "frontend API requests must include the SSO session cookie");
assertIncludes("lib/api.ts", "redirectToMainAppIfNeeded", "frontend API requests must redirect to the main site on SSO 401 responses");
assertIncludes("middleware.ts", "ssoError", "middleware must tell the main site when ticket exchange fails");
assertIncludes("lib/api.ts", "AbortController", "frontend API requests must time out instead of leaving the app loading forever");
assertIncludes("lib/api.ts", "createGenerateImageJob", "image generation must create a backend job instead of holding one long request");
assertIncludes("lib/api.ts", "fetchGenerateImageJob", "image generation must poll the backend generation job");
assertIncludes("lib/api.ts", "pollGenerateImageJob", "image generation must wait for job completion through short polling requests");
assertIncludes("lib/api.ts", "/api/projects/generate/jobs", "frontend image generation must use the backend job endpoint");
assertNotIncludes("lib/api.ts", "timeoutMs: 600000\n    });\n  } catch (error) {\n    rethrowMainAppRedirect(error);\n    return {\n      source: \"demo\"", "image generation must not wait on a single long synchronous request");
assertIncludes("lib/api.ts", "timeoutMs: 180000", "material analysis must keep the request open long enough for model output");
assertIncludes("lib/constants.ts", 'defaults: { size: "2048x2048"', "frontend demo model config must reflect 2K image generation defaults");
assertIncludes("app/page.tsx", "selectedPlatform.generationSize", "main and campaign image generation requests must keep using the selected platform size");
assertIncludes("lib/constants.ts", 'DETAIL_IMAGE_GENERATION_SIZE = "1152x2048"', "detail image generation size must be an explicit 9:16 request size");
assertIncludes("app/page.tsx", "generationSizeForGroup(group)", "detail image generation requests must send the 9:16 size instead of the square platform size");
assertIncludes("app/page.tsx", "generationSizeForModuleId(moduleId)", "detail image regeneration and edits must keep 9:16 sizing");
assertIncludes("app/globals.css", "aspect-ratio: 9 / 16", "detail preview frames must render as 9:16 portraits");
assertIncludes("app/page.tsx", 'const EDIT_IMAGE_MODEL_ID = "primary"', "image edits must pin micro-adjustment to gpt image2(1)");
assertIncludes("app/page.tsx", "editGeneratedImage(imageUrl, trimmed, generationSizeForModuleId(moduleId), EDIT_IMAGE_MODEL_ID, selectedPlatformId)", "image edits must keep the current module group's request size and platform id while using gpt image2(1)");
assertIncludes("lib/api.ts", "createEditImageJob", "image edits must create a backend job instead of holding one long request");
assertIncludes("lib/api.ts", "fetchEditImageJob", "image edits must poll the backend edit job");
assertIncludes("lib/api.ts", "pollEditImageJob", "image edits must wait for job completion through polling");
assertIncludes("lib/api.ts", "/api/projects/edit-image/jobs", "frontend image edits must use the backend edit job endpoint");
assertIncludes("components/ModulesStep.tsx", "选择图片模型", "modules step must expose the image model selector");
assertIncludes("lib/api.ts", "image_model_id: imageModelId", "frontend generation/edit requests must send the selected image model id");
assertIncludes("lib/constants.ts", 'defaultOptionId: "fallback"', "frontend demo model config should default to gpt image2(2)");
assertIncludes("app/page.tsx", "DEFAULT_IMAGE_MODEL_ID", "page should centralize the default image model id");
assertNotIncludes("app/page.tsx", 'useState("primary")', "page should not initialize the image model selector to gpt image2(1)");
assertIncludes("lib/types.ts", 'GenerationMode = "reference_generate" | "fixed_product_composite"', "frontend must model both image generation modes");
assertIncludes("lib/api.ts", "generation_mode: generationMode", "frontend generation requests must send the selected generation mode");
assertIncludes("app/page.tsx", "selectedGenerationMode", "page must keep selected generation mode in state");
assertIncludes("app/page.tsx", "generationMode: input.generationMode", "project snapshots must persist selected generation mode");
assertIncludes("app/page.tsx", "PROJECT_STATE_SCHEMA_VERSION", "project snapshots must carry a schema version for generation-mode migrations");
assertIncludes("app/page.tsx", "normalizeGenerationMode", "restored project state must normalize old fixed-composite defaults back to AI full-image generation");
assertIncludes("components/ModulesStep.tsx", "生成模式", "modules step must expose the generation mode selector");
assertIncludes("components/ModulesStep.tsx", "固定产品合成", "generation mode selector must include fixed product composition");
assertIncludes("components/ModulesStep.tsx", "AI 参考生成（整图）", "generation mode selector should describe AI full-image generation");
assertIncludes("components/ModulesStep.tsx", "生成语言", "modules step must let users choose the generation language before generating");
assertIncludes("components/ModulesStep.tsx", "generationLanguage", "modules step must receive the selected generation language");
assertIncludes("components/ModulesStep.tsx", "Tiếng Việt", "modules step language selector must include Vietnamese");
assertIncludes("app/page.tsx", "selectedGenerationLanguage", "page must keep the step-4 generation language in state");
assertIncludes("app/page.tsx", "targetLanguage: selectedGenerationLanguage", "page must generate selected modules in the step-4 language");
assertIncludes("components/PreviewStep.tsx", "Tiếng Việt", "preview language version choices must include Vietnamese");
assertIncludes("lib/types.ts", '"vi"', "language code type must include Vietnamese");
assertIncludes("components/ModulesStep.tsx", "提示词分支", "modules step must expose the prompt branch selector");
assertIncludes("components/ModulesStep.tsx", "提示词优化分支", "prompt branch selector must include the optimized prompt branch");
assertIncludes("lib/api.ts", "prompt_branch: promptBranch", "frontend generation requests must send the selected prompt branch");
assertIncludes("app/page.tsx", "selectedPromptBranch", "page must keep selected prompt branch in state");
assertIncludes("app/page.tsx", "selectedDetailLayoutId", "page must keep selected detail layout in state");
assertIncludes("app/page.tsx", "detailLayoutId: selectedDetailLayoutId", "page material analysis must use the selected detail layout");
assertIncludes("app/page.tsx", "applyDetailLayoutToModules", "page must apply selected detail layout to detail modules");
assertIncludes("lib/constants.ts", 'DEFAULT_DETAIL_LAYOUT_ID = "detail_evidence_chain_16"', "new projects must default to the evidence-chain detail layout");
assertIncludes("lib/constants.ts", 'id: "detail_ec_auxiliary_mechanism"', "evidence-chain detail layout must include a generic auxiliary mechanism page");
assertIncludes("lib/constants.ts", 'id: "detail_ec_auxiliary_validation"', "evidence-chain detail layout must include a generic auxiliary validation page");
assertNotIncludes("components/ModulesStep.tsx", "固定产品合成（推荐）", "fixed product composition should not be presented as the recommended default");
assertNotIncludes("components/ModulesStep.tsx", "推荐固定产品合成", "fixed product composition help text should not recommend stripping the image into layers by default");
assertIncludes("app/page.tsx", 'const DEFAULT_GENERATION_MODE: GenerationMode = "reference_generate"', "AI full-image generation should be the default generation mode");
assertIncludes("lib/api.ts", 'generationMode: GenerationMode = "reference_generate"', "frontend API default should prefer AI full-image generation");
assertIncludes("lib/constants.ts", 'id: "ingredient_overview"', "detail ingredient section must include a formula overview module");
assertIncludes("lib/constants.ts", 'id: "brand_qualification"', "detail page must include the brand and qualification backing module");
assertIncludes("lib/constants.ts", 'id: "research_strength"', "detail page must include the independent R&D strength module");
assertIncludes("lib/constants.ts", 'id: "product_showcase"', "detail page must include the product showcase reinforcement module");
assertIncludes("lib/constants.ts", 'id: "product_info"', "detail page must include the final product information module");
assertNotIncludes("lib/constants.ts", 'id: "ingredient_1"', "detail ingredient section should no longer split into single-ingredient page 1");
assertNotIncludes("lib/constants.ts", 'id: "ingredient_2"', "detail ingredient section should no longer split into single-ingredient page 2");
assertNotIncludes("lib/constants.ts", 'id: "ingredient_3"', "detail ingredient section should no longer split into single-ingredient page 3");
assertNotIncludes("lib/constants.ts", 'id: "ingredient", name: "成分页"', "detail ingredient section must no longer be a single crowded page");
assertNotIncludes("lib/api.ts", 'source: "demo"', "frontend must not convert failed image generation into fixed demo images");
assertNotIncludes("lib/api.ts", "/assets/generated-cica-asset-sheet.png", "frontend must not mark fixed demo images as generated output");
assert.ok(!fs.existsSync(path.join(root, "lib/autoGenerate.ts")), "lib/autoGenerate.ts: full auto generation flow should be removed");
assert.ok(!fs.existsSync(path.join(root, "components/AutoUploadStep.tsx")), "components/AutoUploadStep.tsx: full auto upload step should be removed");
assert.ok(!fs.existsSync(path.join(root, "components/AutoProgressStep.tsx")), "components/AutoProgressStep.tsx: full auto progress step should be removed");
assert.ok(!fs.existsSync(path.join(root, "components/AutoResultStep.tsx")), "components/AutoResultStep.tsx: full auto result step should be removed");
assertIncludes("components/ModulesStep.tsx", "{platform.name} · 生成 {platform.generationSize}", "platform selector must show the 2K generation size first");
assertIncludes("components/ModulesStep.tsx", "当前版块生成尺寸 {activeGenerationSizeLabel}", "platform summary must show the active image group generation size");
assertIncludes("components/ModulesStep.tsx", "发布参考：主图 {selectedPlatform.mainSize}", "platform summary may show platform publishing size only as a reference");
assertIncludes("components/ModulesStep.tsx", "当前版块生成尺寸 {activeGenerationSizeLabel}", "model panel must show the active image group request size");
assertNotIncludes("components/ModulesStep.tsx", "所选模型默认尺寸", "model panel must not present stale provider defaults as the generated output size");

assertIncludes("components/ReviewStep.tsx", "textarea", "review step must allow editing extracted fields");
assertIncludes("components/ReviewStep.tsx", "onUpdateProductInfo", "review step must propagate edits to page state");
assertIncludes("components/ReviewStep.tsx", "productInfoFieldsForDetailLayout(selectedDetailLayoutId)", "review step fields must follow the selected detail layout");
assertIncludes("lib/productInfo.ts", "第 16 屏：使用方法", "evidence-chain field config must expose all sixteen detail screens");
assertIncludes("lib/productInfo.ts", "第 2 屏：痛点放大", "evidence-chain field config must expose pain screen extraction");
assertIncludes("lib/productInfo.ts", "第 12 屏：辅助功效验证", "evidence-chain field config must expose auxiliary validation screen extraction");
assertIncludes("lib/productInfo.ts", "detail_module:", "shared product info field config must use per-screen detail module fields");
assertIncludes("app/page.tsx", "selectedDetailLayoutId={selectedDetailLayoutId}", "review step must receive the selected detail layout");
assertIncludes("app/page.tsx", "const expandedProductInfo = productInfoWithDetailLayoutFields(mergedProductInfo, selectedDetailLayoutId)", "AI analysis results must be expanded into per-screen detail fields before review");
assertIncludes("lib/productInfo.ts", "material_highlights", "product info helpers must preserve material highlight summaries");
assertIncludes("components/ReviewStep.tsx", "confirmedFields", "review step must track field confirmation");
assertIncludes("components/ReviewStep.tsx", "暂无 AI 提炼结果", "review step must be empty until real AI extraction succeeds");
assertNotIncludes("app/page.tsx", "setProductInfo(defaults.product_info)", "page must not prefill review fields with demo product information");
assertIncludes("app/page.tsx", "hasAiProductInfo ? productInfo : null", "review step must render extracted fields only after a model result");
assertIncludes("app/page.tsx", 'result.source === "model" && result.product_info', "page must require a real model product_info before filling review fields");
assertNotIncludes("lib/api.ts", "DEFAULT_PRODUCT_INFO", "frontend API must not fall back to demo product information");
assertNotIncludes("lib/constants.ts", "DEFAULT_PRODUCT_INFO", "frontend constants must not ship demo product information");

assertIncludes("components/PreviewStep.tsx", "download", "preview step must expose downloadable outputs");
assertIncludes("components/PreviewStep.tsx", "正在调整中", "image edit buttons must show an in-progress label while micro-adjustment is running");
assertIncludes("components/PreviewStep.tsx", "await onEditImage", "image edit buttons must stay in progress until the edit request finishes");
assertIncludes("components/PreviewStep.tsx", "buildDetailDownloadState", "preview detail downloads must be driven by the shared detail download state");
assertIncludes("components/PreviewStep.tsx", "groupedItems.detail.map", "preview step must render every generated detail image in the long preview");
assertNotIncludes("components/PreviewStep.tsx", "generatedImages[0]?.url", "preview step must not use only the first generated image as the full long preview");
assertIncludes("components/PreviewStep.tsx", "createComposeLongImageJob", "preview step must start backend JPEG composition for the full long image");
assertIncludes("components/PreviewStep.tsx", "prepareComposeLongImageSources", "preview step must upload data URL sources before creating the compose job");
assertIncludes("components/PreviewStep.tsx", "fetchComposeLongImageJob", "preview step must poll backend JPEG composition progress");
assertIncludes("components/PreviewStep.tsx", "composeStatus", "preview step must show backend progress during composition");
assertIncludes("components/PreviewStep.tsx", "full-detail.jpg", "full long image export must download a JPG file");
assertNotIncludes("components/PreviewStep.tsx", "full-detail.svg", "full long image export must not download SVG");
assertNotIncludes("components/PreviewStep.tsx", "window.open", "image downloads must not open popup tabs when direct fetch fails");
assertNotIncludes("components/PreviewStep.tsx", "window.location.href = download.url", "long image downloads must not navigate to remote image URLs");
assertIncludes("components/PreviewStep.tsx", "isDirectDownloadUrl", "public image URLs should download directly without backend proxying");
assertIncludes("components/PreviewStep.tsx", "fetch(url)", "public image downloads should fetch R2 images in-browser before creating a download blob");
assertNotIncludes("components/PreviewStep.tsx", "downloadUrl(url, filename)", "cross-origin public image downloads must not use direct anchor URLs because browsers may open them");
assertIncludes("components/PreviewStep.tsx", "handleDownloadVisibleBatch", "preview directory must expose batch download for the active main/campaign group");
assertIncludes("components/PreviewStep.tsx", "index < visibleItems.length", "batch download must only download currently generated images in the active directory");
assertIncludes("components/PreviewStep.tsx", 'activeImageGroup === "detail"', "detail directory must keep compose download separate from main/campaign batch download");
assertIncludes("components/PreviewStep.tsx", "批量下载", "main and campaign directories must show a batch download action");
assertIncludes("components/PreviewStep.tsx", "张详情分图", "detail directory must expose a real split-image batch download, not only a manifest");
assertIncludes("lib/api.ts", "/api/projects/compose-long-image", "frontend API must expose backend long image composition");
assertIncludes("lib/api.ts", "/api/projects/compose-long-image/prepare", "frontend API must expose backend compose source preparation");
assertIncludes("app/page.tsx", "PROJECT_STATE_STORAGE_KEY", "page must define a storage key for preserving generated results");
assertIncludes("app/page.tsx", "localStorage", "page must persist generated results across reloads and step changes");
assertIncludes("app/page.tsx", "restored.generatedImages", "page must restore generated images from saved state");
assertIncludes("app/page.tsx", "window.location.hash", "page must restore active step from the URL hash");
assertIncludes("app/page.tsx", "hashchange", "page must stay in sync when the URL hash changes");
assertIncludes("app/page.tsx", "generationProgress", "page must track generation progress by image group");
assertIncludes("app/page.tsx", "promotionInfo", "page must persist campaign promotion text");
assertIncludes("app/page.tsx", "currentHistoryId", "page must keep the saved history id for later autosaves");
assertIncludes("app/page.tsx", "id: resolveReusableHistoryId(currentHistoryId, null)", "history autosave must reuse the current history id instead of inserting duplicates");
assertIncludes("app/page.tsx", "trackSavedHistoryId: false", "background save before loading a history copy must not reattach the copy workspace to the original history id");
assertIncludes("app/page.tsx", "canSaveHistory={Boolean(productInfo && hasAiProductInfo && generatedImages.length)}", "preview save action must require parsed product information, matching the topbar save action");
assertIncludes("components/PreviewStep.tsx", "canSaveHistory", "preview step must receive an explicit save eligibility flag");
assertIncludes("components/PreviewStep.tsx", "disabled={isSavingHistory || !canSaveHistory}", "preview save action must disable when product info is missing");
assertNotIncludes("components/HistoryDrawer.tsx", "生成图片后会自动保存到这里", "history empty state must not promise autosave after switching to manual save");
assertIncludes("lib/historyApi.ts", "LOCAL_HISTORY_STORAGE_KEY", "history API must keep a local fallback when PostgreSQL is not configured");
assertIncludes("lib/historyApi.ts", "getScopedLocalHistoryStorageKey", "history local fallback key must be scoped by session user");
assertIncludes("lib/historyApi.ts", "detail-image-agent-history:", "history local fallback key must include the current user id");
assertIncludes("lib/historyApi.ts", "fetchCurrentHistoryUserId", "history API must resolve the current SSO user before using local fallback history");
assertIncludes("lib/historyApi.ts", "saveLocalHistory", "history save must persist locally when the backend save fails");
assertIncludes("lib/historyApi.ts", "fetchLocalHistoryList", "history drawer must still show locally saved records when the backend list is empty");
assertIncludes("app/page.tsx", "defaultModules", "page must keep the default module config for a full new-project reset");
assertIncludes("app/page.tsx", "startNewProject", "page must expose a full new-project reset action");
assertIncludes("app/page.tsx", "setSelectedStyleId(styles[0]?.id ?? DEFAULT_STYLE_ID)", "new project reset must restore the default style instead of copying the previous project style");
assertIncludes("app/page.tsx", "setSelectedPlatformId(\"tmall\")", "new project reset must restore the default platform instead of copying the previous project platform");
assertIncludes("app/page.tsx", "setModules(applyDetailLayoutToModules(defaultModules.map((module) => ({ ...module })), DEFAULT_SELECTED_DETAIL_LAYOUT_ID))", "new project reset must restore default detail layout modules instead of copying current module choices");
assertIncludes("app/page.tsx", "mergeRestoredModules(applyDetailLayoutToModules(normalizedDefaultModules, restoredDetailLayoutId), restored.modules, restoredDetailLayoutId)", "restored projects must normalize the restored detail layout ordering");
assertIncludes("app/page.tsx", "const hasOrderChange = normalizedModules.some", "open project state must self-correct stale detail ingredient ordering");
assertIncludes("lib/projectEnhancements.ts", "normalizeDetailIngredientModuleOrder", "module helpers must keep ingredient overview and ingredient explanation pages together");
assertIncludes("app/page.tsx", "setPromotionInfo(\"\")", "new project reset must clear campaign promotion text");
assertIncludes("app/page.tsx", "setReturnWorkspaceSnapshot(null)", "new project reset must discard the previous workspace copy context");
assertNotIncludes("app/page.tsx", "duplicateProjectForNewProduct", "page must not keep copy-project behavior when starting a new project");
assertIncludes("app/page.tsx", "新建项目", "topbar action must communicate a new project reset");
assertNotIncludes("app/page.tsx", "复制项目", "topbar action must not describe the reset as copying");
assertIncludes("app/page.tsx", "returnWorkspaceSnapshot", "page must keep a return snapshot before loading a history copy");
assertIncludes("app/page.tsx", "useAppViewer", "page must load the SSO viewer before account-scoped history behavior");
assertIncludes("app/page.tsx", "setCurrentHistoryId(null)", "loading a history copy must start a new autosave record instead of overwriting the source history");
assertIncludes("app/page.tsx", "返回原工作区", "page must expose a way back to the original workspace after loading a history copy");
assertIncludes("components/HistoryDrawer.tsx", "onRestoreCopy(detail.state, detail.id)", "history drawer must load records as copies rather than continuing the source history id");
assertIncludes("components/HistoryDrawer.tsx", "载入副本", "history drawer restore action must communicate copy semantics");
assertNotIncludes("components/HistoryDrawer.tsx", "onRestore(detail.state, detail.id)", "history drawer must not pass the source history id for autosave reuse");
assertIncludes("lib/api.ts", "promotion_info", "frontend API must send campaign promotion text to backend generation");
assertNotIncludes("app/page.tsx", 'file.slot === "style_reference"', "page generation handler should not collect removed style reference uploads");
assertIncludes("lib/types.ts", 'StyleSource = "preset" | "ai_custom"', "frontend should model only preset and AI custom style sources");
assertIncludes("app/page.tsx", "setStyleSource(\"preset\")", "preset style selection must leave reference style mode");
assertNotIncludes("app/page.tsx", "setStyleSource(\"reference\")", "page should not offer removed reference style mode");
assertIncludes("components/StyleStep.tsx", "styleSource === \"preset\" && style.id === selectedStyleId", "preset cards must only be selected in preset style mode");
assertNotIncludes("components/StyleStep.tsx", "styleSource === \"reference\"", "style step should not render removed reference style mode");
assertNotIncludes("components/StyleStep.tsx", "onStyleReferenceSelect", "style step should not expose removed reference style handler");
assertIncludes("lib/api.ts", "planAiCustomStyle", "frontend API must expose Gemini custom style planning");
assertIncludes("lib/api.ts", "/api/projects/plan-style", "frontend API must call the backend style planning endpoint");
assertIncludes("lib/api.ts", "analyzeStyleReference", "frontend API must expose Gemini benchmark image style analysis");
assertIncludes("lib/api.ts", "/api/projects/analyze-style-reference", "frontend API must call the backend benchmark style analysis endpoint");
assertIncludes("lib/constants.ts", 'id: "space_repair"', "frontend preset styles must include space repair as a normal style option");
assertIncludes("lib/constants.ts", 'id: "black_gold_luxury"', "frontend preset styles must include black gold luxury as a normal style option");
assertNotIncludes("lib/constants.ts", 'id: "green_repair"', "frontend preset styles must remove the old green repair preset");
assertNotIncludes("lib/constants.ts", 'id: "blue_hydration"', "frontend preset styles must remove the old blue hydration preset");
assertNotIncludes("lib/constants.ts", 'id: "gold_antiaging"', "frontend preset styles must remove the old gold antiaging preset");
assertIncludes("app/page.tsx", 'const DEFAULT_STYLE_ID = "space_repair"', "default style should point to the first remaining preset");
assertIncludes("components/StyleStep.tsx", "styleThemePreview", "style step must render structured preset cards even without image assets");
assertNotIncludes("components/StyleStep.tsx", "护肤风格灵感", "structured preset styles must not live inside the AI custom card");
assertNotIncludes("app/page.tsx", "AI_CUSTOM_STYLE_PRESETS", "page must not pass structured presets into AI custom planning");
assertNotIncludes("lib/api.ts", "style_preset", "frontend style planning request must not send preset seeds");
[
  "style-space-repair.png",
  "style-deep-sea-hydration.png",
  "style-lab-clinical-tech.png",
  "style-oriental-herbal.png",
  "style-glacier-cooling.png",
  "style-floral-fragrance.png",
  "style-black-gold-luxury.png"
].forEach((asset) => {
  const assetPath = path.join(root, "public", "assets", asset);
  assert.ok(fs.existsSync(assetPath), `public/assets/${asset}: structured preset preview image must exist`);
  assert.equal(fs.readFileSync(assetPath).subarray(0, 8).toString("hex"), "89504e470d0a1a0a", `public/assets/${asset}: preset preview must be a PNG bitmap generated by the image model`);
});
assertNotIncludes("lib/api.ts", "category,", "custom style planning must not send a manually selected category");
assertNotIncludes("app/page.tsx", "planAiCustomStyle(productInfo, selectedCategory", "custom style planning must rely on AI product_info category");
assertNotIncludes("app/page.tsx", "productInfo.category || selectedCategory", "history records must not fall back to a manually selected category");
assertIncludes("lib/api.ts", "product_images: productImages", "custom style planning must send product images directly to Gemini");
assertIncludes("lib/api.ts", "generateAiCustomStyleSample", "frontend API must expose custom style sample generation");
assertIncludes("lib/api.ts", "/api/projects/plan-style-sample", "frontend API must call the style sample endpoint separately");
assertIncludes("lib/types.ts", "SavedStyleRecord", "frontend must type account saved style records");
assertIncludes("lib/api.ts", "fetchSavedStyles", "frontend API must list account saved styles");
assertIncludes("lib/api.ts", "saveSavedStyle", "frontend API must save a Gemini style to the account library");
assertIncludes("lib/api.ts", "deleteSavedStyle", "frontend API must delete an account saved style");
assertIncludes("lib/api.ts", "/api/styles/saved", "frontend API must call the account saved styles endpoint");
assertNotIncludes("lib/types.ts", "savedStyles: SavedStyleRecord[]", "project state must not persist the account saved style library");
assertIncludes("components/StyleStep.tsx", "保存到我的风格", "AI custom style card must let users save good Gemini styles");
assertIncludes("components/StyleStep.tsx", "我的保存风格", "style step must render account saved styles");
assertIncludes("components/StyleStep.tsx", "onSelectSavedStyle", "style step must expose saved style selection");
assertIncludes("components/StyleStep.tsx", "onDeleteSavedStyle", "style step must expose saved style deletion");
assertIncludes("app/page.tsx", "fetchSavedStyles", "page must load account saved styles");
assertIncludes("app/page.tsx", "saveSavedStyle", "page must save the current Gemini style to the account library");
assertIncludes("app/page.tsx", "deleteSavedStyle", "page must delete account saved styles");
assertNotIncludes("app/page.tsx", "savedStyles: input.savedStyles", "project state snapshots must not include account saved styles");
assertNotIncludes("components/StyleStep.tsx", "Gemini 产品视觉建议", "style step must not display a separate product visual suggestion panel");
assertNotIncludes("app/page.tsx", "setProductVisualSuggestion", "page must not store separate visual suggestions before style planning");
assertIncludes("app/page.tsx", "const productImages = uploadedFiles", "page must collect uploaded product images for Gemini style planning");
assertIncludes("app/page.tsx", "customStyle", "page must store the Gemini-planned custom style");
assertIncludes("app/page.tsx", "planAiCustomStyle", "page must call Gemini only from the AI custom style action");
assertIncludes("app/page.tsx", "styleReferenceFiles", "page must store uploaded benchmark reference images separately from product files");
assertIncludes("app/page.tsx", "handleAnalyzeStyleReference", "page must analyze benchmark reference images through Gemini");
assertIncludes("app/page.tsx", "styleReferenceImages", "generation must collect benchmark reference image URLs");
assertIncludes("app/page.tsx", "generateAiCustomStyleSample", "page must generate AI style samples only from the separate sample action");
assertIncludes("app/page.tsx", "styleSource === \"ai_custom\" ? customStyle", "generation must send the selected AI custom style brief");
assertIncludes("components/StyleStep.tsx", "customStyle.asset", "AI custom style card must render the generated GPT image sample when available");
assertIncludes("components/StyleStep.tsx", "让 AI 规划风格", "AI custom style action must only communicate style planning");

assertIncludes("components/PreviewStep.tsx", "Gemini 图片合规复查", "preview image compliance action must use Gemini recognition wording");
assertIncludes("app/page.tsx", "正在进行 Gemini 图片合规复查", "page status must communicate Gemini image review");
assertIncludes("lib/api.ts", "请重试 Gemini 图片合规复查", "frontend fallback must not mention OCR for image review failures");
assertNotIncludes("components/PreviewStep.tsx", "OCR", "preview image compliance UI must not mention OCR");
assertNotIncludes("app/page.tsx", "OCR", "page image compliance status must not mention OCR");
assertNotIncludes("lib/api.ts", "OCR", "frontend image compliance fallback must not mention OCR");
assertIncludes("components/StyleStep.tsx", "生成样例图", "AI custom style card must expose separate sample generation");
assertIncludes("components/StyleStep.tsx", "规划统一视觉元素", "AI custom style copy should emphasize style elements instead of one overall color");
assertIncludes("components/StyleStep.tsx", "每张图可按模块变化颜色", "AI custom style copy should say colors may vary by module");
assertNotIncludes("components/StyleStep.tsx", "包装色规划", "AI custom style copy should not imply planning one overall color from packaging");
assertNotIncludes("app/page.tsx", "WHITE_BACKGROUND_MODULE_IDS", "product image requirements should apply to every generated image, not only white-background modules");
assertNotIncludes("app/page.tsx", "白底图需要先上传产品图", "product image requirement copy should not imply only white-background modules need the original product image");
assertIncludes("lib/types.ts", "uploadedFiles: UploadedFileInfo[]", "persisted project state must include uploaded files so history can restore product images");
assertIncludes("app/page.tsx", "uploadedFiles: input.uploadedFiles", "project snapshots must persist uploaded files");
assertIncludes("app/page.tsx", "setUploadedFiles(restored.uploadedFiles ?? [])", "local project restore must restore uploaded files");
assertIncludes("app/page.tsx", "setUploadedFiles(state.uploadedFiles ?? [])", "history restore must restore uploaded files");
assertNotIncludes("app/page.tsx", "setUploadedFiles([]);\n    setManualFieldKeys([]);\n    setAnalysisSource(historyId", "history restore must not clear uploaded product images");
assertIncludes("app/page.tsx", "请先上传产品图，避免生成结果与原产品不一致", "all image generation should require product images for consistency");
assertIncludes("components/StyleStep.tsx", "AI 自定义风格", "style step must show an AI custom style option");
assertNotIncludes("components/StyleStep.tsx", "Gemini 3.1 Pro</em>", "AI custom style card must not show a Gemini model badge");
assertIncludes("components/StyleStep.tsx", "aiPlanButton", "AI planning action should sit lower in the custom style card");
assertIncludes("components/StyleStep.tsx", "onPlanAiCustomStyle", "style step must expose a click handler for Gemini style planning");
assertIncludes("components/StyleStep.tsx", "onGenerateAiStyleSample", "style step must expose a separate sample generation handler");
assertIncludes("components/ModulesStep.tsx", "促销方式", "modules step must let users enter campaign promotion text");
assertIncludes("components/ModulesStep.tsx", "campaign", "modules step must expose campaign image generation group");
assertIncludes("components/PreviewStep.tsx", "campaign", "preview step must expose campaign image results");
assertIncludes("components/ModulesStep.tsx", "disabled={activeProgress.isGenerating}", "generation button must prevent duplicate submissions per image group");
assertIncludes("app/page.tsx", "runningModuleIds", "page generation progress must track every concurrently running module");
assertIncludes("app/page.tsx", "onRetry: (module, attempt, retryAttempts, delayMs, errors)", "page generation should surface automatic retry status for transient image model failures");
assertIncludes("lib/projectEnhancements.ts", "isRetryableImageGenerationError", "image generation retries must only target transient network/server failures");
assertIncludes("lib/projectEnhancements.ts", "DEFAULT_IMAGE_GENERATION_RETRY_ATTEMPTS = 2", "image generation should retry transient failures twice by default");
assertIncludes("components/ModulesStep.tsx", "(activeProgress.runningModuleIds ?? []).includes(module.id)", "modules step must show every concurrently running module as generating and tolerate restored progress state");
assertIncludes("components/PreviewStep.tsx", "(activeProgress.runningModuleIds ?? []).includes(module.id)", "preview step must show every concurrently running module as generating and tolerate restored progress state");
assertIncludes("app/page.tsx", "targetModuleId", "page generation handler must support a single target module");
assertIncludes("components/ModulesStep.tsx", "stopPropagation", "per-module generation buttons must not toggle module selection");
assertIncludes("components/ModulesStep.tsx", "重新生成", "modules step must expose regenerate actions");
assertIncludes("components/PreviewStep.tsx", "onGenerateModule", "preview step must trigger per-module regeneration");
assertIncludes("components/ModulesStep.tsx", "role=\"button\"", "module rows must remain keyboard-accessible after adding nested action buttons");
assertIncludes("components/ModulesStep.tsx", "preventDefault", "keyboard module toggles must not scroll the page");
assertIncludes("components/PreviewStep.tsx", "重新生成", "preview step must expose regenerate actions");
assertNotIncludes("components/PreviewStep.tsx", 'moduleUrl ? "重新生成" : "生成"', "preview directory must not render regenerate buttons");
assertIncludes("components/PreviewStep.tsx", "directoryDownloadSlot", "preview directory download buttons must use an aligned action slot");
assertIncludes("components/PreviewStep.tsx", "downloadFilenameForModule(item.module", "detail preview cards must expose per-module download actions for newly added detail screens");
assertIncludes("lib/api.ts", "target_language: targetLanguage", "frontend generation requests must pass target language for full-image language regeneration");
assertIncludes("components/PreviewStep.tsx", "languageOptions", "preview step must expose language version choices");
assertIncludes("components/PreviewStep.tsx", "`生成 ${language.label}`", "preview step must let users generate missing language versions");
assertIncludes("app/page.tsx", "targetLanguage: language", "page must regenerate a full image when creating a missing language version");
assertNotIncludes("app/page.tsx", "renderLanguageVersion(version.baseUrl, version.textLayers", "page must not render translated text layers over the old base image");
assertIncludes("lib/api.ts", "/api/projects/compliance/check-text", "frontend API must expose text compliance checks");
assertIncludes("lib/api.ts", "/api/projects/compliance/check-images", "frontend API must expose image compliance checks");
assertIncludes("lib/api.ts", "text_compliance_request_failed", "text compliance request failures must require manual review");
assertIncludes("components/ReviewStep.tsx", "合规风险", "review step must show product-info compliance risks");
assertIncludes("components/ModulesStep.tsx", "促销合规预检", "modules step must show campaign promotion compliance preflight");
assertIncludes("components/PreviewStep.tsx", "ComplianceBadge", "preview step must render compliance badges on generated images");
assertIncludes("components/PreviewStep.tsx", "导出前合规提示", "preview export area must summarize selected image compliance");
assertIncludes("components/PreviewStep.tsx", "Gemini 图片合规复查", "preview export area must let users scan final images with Gemini before export");
assertIncludes("app/globals.css", "complianceBadge", "global styles must include compliance badge styling");
assertIncludes("app/globals.css", "complianceIssueList", "global styles must include compliance issue list styling");

console.log("Static UI contract checks passed.");
